Repository canonical/webteam-hubot, pull requests merged in 2020-07, with the labels that each got.

#75 Add mattermost support
  .env
  .gitignore
  deploy/site.yaml
  package.json
  scripts/github-action-notification.js
  scripts/github-pull-requests-reviews-notifications.js
  scripts/release-notifications.coffee
  scripts/rt-portal.coffee
  scripts/support.js
  yarn.lock
Labels: Review: Code +1, Review: QA +1

#80 Add logs for acronym requested
  scripts/acronyms.js
Labels: Review: Code +1, Review: QA +1

#81 Add repo name on pull request notification
  scripts/pull-request-notifications.coffee
Labels: Review: Code +1

#82 Fix typo error message
  scripts/acronyms.js
Labels: Review: Code +1

#83 Rename deploy to konf
  konf/site.yaml
Labels: Review: QA +1

#84 Add Sentry DSN to site.yaml
  konf/site.yaml
Labels: Review: Code needed, Review: QA needed
