Repository canonical/webteam-hubot, pull requests merged in 2020-06, with the labels that each got.

#71 Add k8s configuration in deploy/site.yaml
  README.md
  deploy/site.yaml
Labels: Review: Code +1

#69 Use ubuntu image for node js build step
  Dockerfile
Labels: Review: Code +1, Review: QA +1

#72 Add acronym endpoint for mattermost
  Dockerfile
  scripts/acronyms.js
Labels: Review: Code +1, Review: QA +1

#73 Update deployment config
  deploy/site.yaml
Labels: Review: Code needed

#74 Update response_type from in_channel to ephemeral
  scripts/acronyms.js
Labels: Review: Code +1
