Repository canonical/webteam-hubot, pull requests merged in 2022-05, with the labels that each got.

#145 Explain bot
  konf/site.yaml
  scripts/explain.js
Labels: Review: Code +1, Review: QA +1, Blocked ⛔

#149 fix table markdown syntax
  scripts/explain.js
Labels: Review: Code +1

#154 Fix explain command table
  scripts/explain.js
Labels: Review: Code +1, Review: QA +1
